apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: carts-api
  description: API for the Carts Service
spec:
  type: swagger
  lifecycle: development
  owner: user:guest
  definition:
    $text: https://github.com/infracloudio/backstage-msvc-app/blob/main/src/cartservice/api-catalog/open-api.yaml
