apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: boutique-frontend
  annotations:
    github.com/project-slug: infracloudio/backstage-msvc-app/src/frontend
spec:
  type: service
  lifecycle: production
  owner: user:guest
